version: '3.8'

services:
  # Baza danych PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: adamgolik113
      POSTGRES_DB: go2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: adamgolik113
      DB_NAME: go2
      SECRET_KEY: qzawxsecdrvftbgyhnujimko,1234567890-=
    depends_on:
      - postgres
    networks:
      - app_network

  # Frontend
  frontend:
    build:
      context: ./frontend          # Katalog frontendu, gdzie znajduje się Dockerfile
      dockerfile: Dockerfile       # Plik Dockerfile w katalogu frontendu
    container_name: frontend_container
    restart: always
    ports:
      - "8081:3000"                # Port 3000 dla aplikacji React (Next.js)
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
